Algoritmo "Questão 6"

  //Aluno: Alexandre Santana Nunes

Var
notaUm : real
notaDois : real
media : real

Inicio
escreva("Digite sua primeira nota: ")
leia(notaUm)

escreva("Digite sua segunda nota: ")
leia(notaDois)

media <- (notaUm+notaDois)/2

escreval("Sua média é:", media)

se(Media >= 6) então
escreval("Parabéns você foi aprovado!")
senão
escreval("Sinto muito, você foi reprovado.")
fimse

Fimalgoritmo